---
name: Lint

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "18.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: solid

      - name: Lint
        run: yarn run lint
        working-directory: solid

  repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Install yamllint
        run: |
          pipx install yamllint

      - name: Lint repos.yaml
        run: |
          yamllint -f github ./repos.yaml
