---
name: Lint

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "18.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: solid

      - name: Lint
        run: yarn run lint
        working-directory: solid

  repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install yamllint
        run: |
          pipx install yamllint

      - name: Lint repos.yaml
        run: |
          yamllint -f github ./repos.yaml
